[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "sublime-lojoja-colors"
version = "1.1.7a0"
description = "A collection of color schemes for Sublime Text with extended scope, language, and package support."
license = {text = "MIT"}
readme = "README.md"
authors = [
  { name = "lojoja", email = "dev@lojoja.com" }
]
requires-python = ">=3.11,<4"
dependencies = [
  "pydantic>=2.10.4,<3"
]
dynamic = ["classifiers"]

[project.urls]
homepage = "https://github.com/lojoja/sublime-lojoja-colors"
repository = "https://github.com/lojoja/sublime-lojoja-colors"
"Bug Tracker" = "https://github.com/lojoja/sublime-lojoja-colors/issues"

[project.scripts]
build = "sublime_lojoja_colors:build"
schema = "sublime_lojoja_colors:config_schema"
validate = "sublime_lojoja_colors:validate"

[tool.poetry]
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
]
packages = [
    {include = "sublime_lojoja_colors.py", from = "src"}
]

[tool.poetry.group.dev.dependencies]
black = "^25.11.0"
pylint = "^4.0.3"
pyright = "^1.1.407"
pytest = "^9.0.1"
pytest-cov = "^7.0.0"
pytest-mock = "^3.15.1"

[tool.black]
include = '\.pyi?$'
line-length = 120
skip-magic-trailing-comma = true
target_version = ["py311"]

[tool.coverage.run]
source = ["src"]
omit = ["tests/"]
branch = true

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if log:",
]
fail_under = 100
show_missing = true

[tool.pylint.main]
ignore-paths = ["^(.*/)?.venv/.*$"]
load-plugins = ["pylint.extensions.mccabe"]

[tool.pylint.design]
max-complexity = 15

[tool.pylint.format]
max-line-length = 120

[tool.pyright]
ignore = [".venv/*"]
pythonVersion = "3.11"
venv = ".venv"
venvPath = "."

[tool.pytest.ini_options]
addopts = "--strict-markers"
pythonpath = ["src"]
testpaths = ["tests"]
markers = []
filterwarnings = ["ignore:::.*pytest_cov*"]
