[project]
name = "sublime-lojoja-colors"
version = "1.1.7a0"
description = "A collection of color schemes for Sublime Text with extended scope, language, and package support."
authors = [{ name = "lojoja", email = "dev@lojoja.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = ["pydantic>=2.13.4,<3"]

[project.scripts]
build = "sublime_lojoja_colors:build"
schema = "sublime_lojoja_colors:config_schema"
validate = "sublime_lojoja_colors:validate"

[project.urls]
homepage = "https://github.com/lojoja/sublime-lojoja-colors"
repository = "https://github.com/lojoja/sublime-lojoja-colors"
"Bug Tracker" = "https://github.com/lojoja/sublime-lojoja-colors/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1,<10",
    "pytest-cov>=7.0.0,<8",
    "pytest-mock>=3.15.1,<4",
    "ruff>=0.15.21",
    "ty>=0.0.59",
]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.run]
source = ["src"]
omit = ["tests"]
branch = true

[tool.hatch.build]
sources = ["src"]

[tool.hatch.build.targets.wheel]
include = ["*.py", "data/"]
exclude = ["tests/**"]

[tool.pytest]
pythonpath = ["src"]
testpaths = ["tests"]
strict_markers = true
markers = []
filterwarnings = []

[tool.ruff]
src = ["src", "tests"]
target-version = "py311"
line-length = 120

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["COM812", "D203", "D213", "E111", "E114", "E117"]
fixable = ["ALL"]
unfixable = []
mccabe.max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "FBT001",
  "INP001",
  "PLR0913",
  "S101"
]

[tool.ty]
src.include = ["src", "tests"]
