name: Validate

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  validate:
    name: Validate color schemes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.11
          cache: poetry
      - name: Install project
        run: poetry install
      - name: Run validation
        run: poetry run validate
