name: Validate

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  validate:
    name: Validate color schemes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Install poetry
        run: pipx install poetry
      - name: Set up python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d
        with:
          python-version: 3.11
          cache: poetry
      - name: Install project
        run: poetry install
      - name: Run validation
        run: poetry run validate
